<?php

namespace Database\Seeders;

use App\Models\AlamatModel;
use App\Models\KkModel;
use App\Models\PendudukModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PendudukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $penduduk =
            [
                [
                    'nik' => '3522110504040001',
                    'nama' => "Ridho Aulia' Rahman",
                    'tempat_lahir' => 'Bojonegoro',
                    'tgl_lahir' => '2004-05-04',
                    'jenis_kelamin' => 'Laki-Laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'O',
                    'no_kk' => '3522110504040001',
                    'no_hp' => '083193985902',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => '1',
                    'image' => url('assets/images/user/user-01.png')
                ],
                [
                    'nik' => '3522110504040002',
                    'nama' => "Anang",
                    'tempat_lahir' => 'Bojonegoro',
                    'tgl_lahir' => '2004-05-04',
                    'jenis_kelamin' => 'Laki-Laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'O',
                    'no_kk' => '3522110504040001',
                    'no_hp' => '081234567890',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => '2',
                    'image' => url('assets/images/user/user-01.png')
                ],
                [
                    'nik' => '3522110504040003',
                    'nama' => "Abid",
                    'tempat_lahir' => 'Bojonegoro',
                    'tgl_lahir' => '2004-05-04',
                    'jenis_kelamin' => 'Laki-Laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'O',
                    'no_kk' => '3522110504040001',
                    'no_hp' => '081234567890',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => '3',
                    'image' => url('assets/images/user/user-01.png')
                ],
                [
                    'nik' => '3522110504040004',
                    'nama' => "Putra",
                    'tempat_lahir' => 'Bojonegoro',
                    'tgl_lahir' => '2004-05-04',
                    'jenis_kelamin' => 'Laki-Laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'O',
                    'no_kk' => '3522110504040001',
                    'no_hp' => '081234567890',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => '4',
                    'image' => url('assets/images/user/user-01.png')
                ],
                [
                    'nik' => '3522110504040005',
                    'nama' => "Zaki",
                    'tempat_lahir' => 'Bojonegoro',
                    'tgl_lahir' => '2004-05-04',
                    'jenis_kelamin' => 'Laki-Laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'O',
                    'no_kk' => '3522110504040001',
                    'no_hp' => '081234567890',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => '5',
                    'image' => url('assets/images/user/user-01.png')
                ],
                [
                    'nik' => '3522110504040006',
                    'nama' => "Jokowi",
                    'tempat_lahir' => 'Pomorogo',
                    'tgl_lahir' => '2006-04-15',
                    'jenis_kelamin' => 'Perempuan',
                    'agama' => 'Hindu',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'B',
                    'no_kk' => '3522110504040002',
                    'no_hp' => '081234512393',
                    'status_penduduk' => 'Penduduk Tetap',
                    'id_alamat' => '6',
                    'image' => url('assets/images/user/user-01.png')
                ],
                [
                    'nik' => '3522110504040007',
                    'nama' => "Budi Setiawan",
                    'tempat_lahir' => 'Malang',
                    'tgl_lahir' => '1985-01-01',
                    'jenis_kelamin' => 'Laki-laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Kawin',
                    'pekerjaan' => 'Pegawai Swasta',
                    'gol_darah' => 'A',
                    'no_kk' => '3522110504040003',
                    'no_hp' => '081234567890',
                    'status_penduduk' => 'Penduduk Tetap',
                    'id_alamat' => 7,
                    'image' => url('assets/images/user/user-02.png'),
                ],
                [
                    'nik' => '3522110504040008',
                    'nama' => "Ani Lestari",
                    'tempat_lahir' => 'Surabaya',
                    'tgl_lahir' => '1990-07-17',
                    'jenis_kelamin' => 'Perempuan',
                    'agama' => 'Kristen',
                    'status_perkawinan' => 'Kawin',
                    'pekerjaan' => 'Ibu Rumah Tangga',
                    'gol_darah' => 'AB',
                    'no_kk' => '3522110504040004',
                    'no_hp' => '085728394051',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => 8,
                    'image' => url('assets/images/user/user-03.png'),
                ],
                [
                    'nik' => '3522110504040009',
                    'nama' => "Dimas Pratama",
                    'tempat_lahir' => 'Jember',
                    'tgl_lahir' => '1995-03-23',
                    'jenis_kelamin' => 'Laki-laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Mahasiswa',
                    'gol_darah' => 'O',
                    'no_kk' => '3522110504040005',
                    'no_hp' => '081234578901',
                    'status_penduduk' => 'Penduduk Tetap',
                    'id_alamat' => 9,
                    'image' => url('assets/images/user/user-04.png'),
                ],
                [
                    'nik' => '3522110504040010',
                    'nama' => "Rina Sari",
                    'tempat_lahir' => 'Blitar',
                    'tgl_lahir' => '1998-12-08',
                    'jenis_kelamin' => 'Perempuan',
                    'agama' => 'Katolik',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Wiraswasta',
                    'gol_darah' => 'AB',
                    'no_kk' => '3522110504040004',
                    'no_hp' => '085678901234',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => 10,
                    'image' => url('assets/images/user/user-05.png'),
                ],
                [
                    'nik' => '3522110504040011',
                    'nama' => "Andi Setiawan",
                    'tempat_lahir' => 'Kediri',
                    'tgl_lahir' => '2002-05-14',
                    'jenis_kelamin' => 'Laki-laki',
                    'agama' => 'Islam',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Pelajar',
                    'gol_darah' => 'B',
                    'no_kk' => '3522110504040001',
                    'no_hp' => '087890123456',
                    'status_penduduk' => 'Penduduk Tetap',
                    'id_alamat' => 11,
                    'image' => url('assets/images/user/user-06.png'),
                ],
                [
                    'nik' => '3522110504040012',
                    'nama' => "Bella Puspita",
                    'tempat_lahir' => 'Probolinggo',
                    'tgl_lahir' => '2000-11-21',
                    'jenis_kelamin' => 'Perempuan',
                    'agama' => 'Hindu',
                    'status_perkawinan' => 'Belum Kawin',
                    'pekerjaan' => 'Mahasiswa',
                    'gol_darah' => 'A',
                    'no_kk' => '3522110504040003',
                    'no_hp' => '089012345678',
                    'status_penduduk' => 'Pendatang',
                    'id_alamat' => 12,
                    'image' => url('assets/images/user/user-07.png'),
                ],
            ];
        PendudukModel::insert($penduduk);
    }
}
